services:
  postgres:
    image: postgres:16-alpine
    container_name: recruiter-postgres
    environment:
      POSTGRES_DB: recruiter_platform
      POSTGRES_USER: recruiter
      POSTGRES_PASSWORD: recruiter_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruiter -d recruiter_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: recruiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 